hydra:
  job:
    chdir: True

random:
  seed: 42

device: cuda:0
use_torch_compile: true
num_eval_envs: 5

# Logger
logger:
  backend: wandb
  mode: online
  exp_name: ppo_maneuver_no_vec_hgauss_fast
  project: aircraft_control_demo
  test_interval: 100_000
  save_interval: 1_000_000
  eval_interval: 500_000
  num_test_episodes: 5


# collector
collector:
  total_frames: 80_000_000
  frames_per_batch: 40000 #max_episode_steps * env_per_collector
  #frames_per_batch: 2_000 #max_episode_steps * env_per_collector
  device: cpu
  env_per_collector: 20
  #env_per_collector: 1

ppo:
  gae_lambda: 0.95
  gamma: 0.99
  clip_epsilon: 0.2
  entropy_coef: 0.0
  epochs: 10
  loss_critic_type: l2 #l2, hgauss

network:
  nbins: 101
  vmin: -100
  vmax: 100
  rmin: -100
  rmax: 1
  
env:
  max_time_steps_train: 1200
  max_time_steps_eval: 2400
  
optim:
  lr_policy: 3.0e-4
  lr_value: 3.0e-3
  critic_coef: 1.0
  weight_decay: 0.0
  #mini_batch_size: 2000
  mini_batch_size: 8000
#  max_grad_norm: 10.0
  anneal_lr: false
  anneal_clip_epsilon: false
  eps: 1.0e-4
  cudagraphs: false